#!/bin/bash

(
	echo 'package interpreter' &&
	echo &&
	echo '// This file is generated by make-prelude.sh -- do not edit it!' &&
	echo '// Instead, edit prelude.lisp.' &&
	echo &&
	echo '// Prelude contains the prelude -- the standard library functions implemented' &&
	echo '// in-language.' &&
	echo 'const Prelude = `; Begin prelude' &&
	echo &&
	sed 's/`/` + "`" + `/g' prelude.lisp &&
	echo '`';
) > prelude.go;
